import { defineConfig } from 'astro/config';

// GitHub username — replace for your fork
const user = 'miwtoo';

export default defineConfig({
  site: `https://${user}.github.io`,
  base: '/my-optcg-binder',
  output: 'static',
  trailingSlash: 'never',
  build: {
    // Assets generated by scripts/generate.js live here
    assets: 'assets',
  },
});
